server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost/diseaseControlSystem
    username: postgres
    password: 202172Sev
  jpa:
    generate-ddl: true

jwt:
  token:
    secret: jwtappdemo
    duration:
      minutes: 30
