server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost/diseaseControlSystem
    username: postgres
    password: 202172Sev
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    username: forlikhvatovtestprojects@gmail.com
    password: zycelztnnhmelxnk
    port: 465
    protocol: smtps

mail:
  debug: true

activationCode:
  duration:
    hours: 24

api:
  prefix: /api/v1
  endpoints:
    roleAdmin:
      /api/v1/admin/**
    roleStudent:
      /api/v1/student/**
    permitAll:
      /api/v1/auth/login,
      /api/v1/auth/registration,
      /api/v1/auth/activate,
      /api/v1/auth/code/resend


vue-client:
  url: http://localhost:8080
  confirm-register-path: /registration/activate
  login: /login


jwt:
  token:
    secret: jwtappdemo
    duration:
      minutes: 30


upload:
  path: /Users/ivanlikhvatov/AllProjects/JavaProjects/SpringRestProjects/disease-control-system/uploads/