server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost/diseaseControlSystem
    username: postgres
    password: 202172Sev
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    username: forlikhvatovtestprojects@gmail.com
    password: hirkeF-kykja6-hafkoh
    port: 587
    protocol: smtp

api:
  prefix: /api/v1
  endpoints:
    login: /api/v1/auth/login
    registration: /api/v1/auth/registration
    admin: /api/v1/admin

mail:
  debug: true

vue-client:
  url: http://localhost:8081
  confirm-register-path: /auth/activate/
  login: /login


jwt:
  token:
    secret: jwtappdemo
    duration:
      minutes: 30
